/* ===========================================================
   Dastarkhwan — recipe data
   Each recipe: slug, name, category, prepTime, cookTime, servings,
   difficulty, excerpt, ingredients[], steps[], tip
   =========================================================== */
const RECIPES = [
  {
    slug: "chicken-biryani",
    name: "Chicken Biryani",
    category: "Rice & Biryani",
    icon: "🍚",
    prepTime: "25 min",
    cookTime: "50 min",
    servings: "6",
    difficulty: "Medium",
    excerpt: "Layered basmati rice and spiced chicken, finished on dum until the whole house smells like it.",
    ingredients: [
      "1 kg chicken, cut into pieces",
      "600 g basmati rice, soaked 30 min",
      "3 large onions, thinly sliced and fried golden (reserve half for layering)",
      "1 cup plain yogurt",
      "3 tbsp ginger-garlic paste",
      "4 tomatoes, chopped",
      "3–4 green chillies, slit",
      "2 tbsp biryani masala powder",
      "1 tsp red chilli powder",
      "1 tsp turmeric powder",
      "Handful mint and coriander leaves, chopped",
      "A pinch of saffron soaked in 3 tbsp warm milk",
      "Whole spices: 4 cloves, 2 black cardamom, 4 green cardamom, 1 cinnamon stick, 2 bay leaves",
      "1/2 cup cooking oil or ghee",
      "Salt to taste"
    ],
    steps: [
      "Heat oil in a heavy-bottomed pot and fry the whole spices for a minute until fragrant.",
      "Add ginger-garlic paste and cook until the raw smell disappears, then add chicken and sear on high heat for 5 minutes.",
      "Add tomatoes, yogurt, red chilli powder, turmeric, biryani masala, and half the fried onions. Cook covered on medium heat for 15–20 minutes until the chicken is tender and the oil separates.",
      "Stir in half the mint and coriander, then turn off the heat — this is your chicken korma base.",
      "Separately, boil the soaked rice in salted water with a bay leaf until 70% done (still firm at the centre), then drain.",
      "Layer half the rice over the chicken korma, scatter the remaining fried onions, mint, and coriander, then top with the rest of the rice.",
      "Drizzle the saffron milk over the top layer, cover tightly with foil and a lid, and cook on very low heat (dum) for 20–25 minutes.",
      "Rest for 10 minutes off the heat, then fluff gently from the sides before serving."
    ],
    tip: "Don't skip resting the biryani before opening the lid — it lets the layers settle so the rice doesn't turn mushy when you mix it."
  },
  {
    slug: "chicken-karahi",
    name: "Chicken Karahi",
    category: "Curry",
    icon: "🍛",
    prepTime: "10 min",
    cookTime: "35 min",
    servings: "4",
    difficulty: "Easy",
    excerpt: "Tomato-forward, ginger-heavy, and cooked hot and fast — the karahi that started as a truck-stop classic.",
    ingredients: [
      "1 kg chicken, cut into medium pieces",
      "5 large tomatoes, roughly chopped",
      "1/2 cup cooking oil",
      "2 tbsp ginger-garlic paste",
      "4–5 green chillies, slit",
      "1 tsp red chilli flakes",
      "1 tsp whole black peppercorns, crushed",
      "1 tsp cumin seeds",
      "1 tbsp julienned ginger, for garnish",
      "Fresh coriander, chopped",
      "Salt to taste"
    ],
    steps: [
      "Heat oil in a karahi or wok until very hot, then add chicken pieces and sear on high heat for 6–7 minutes.",
      "Add ginger-garlic paste and cumin seeds, stirring for 2 minutes until fragrant.",
      "Add chopped tomatoes and salt, cover, and cook on medium-high heat for 12–15 minutes, mashing occasionally, until the tomatoes break down into a thick sauce.",
      "Add green chillies, red chilli flakes, and crushed black pepper, then cook uncovered for another 5 minutes until the oil rises to the top.",
      "Adjust salt, garnish with julienned ginger and coriander, and serve straight from the karahi with naan."
    ],
    tip: "Resist adding water — the tomatoes and chicken release enough liquid, and a dry-ish karahi has better flavour than a watery one."
  },
  {
    slug: "beef-nihari",
    name: "Beef Nihari",
    category: "Curry",
    icon: "🍛",
    prepTime: "20 min",
    cookTime: "4 hr",
    servings: "6",
    difficulty: "Hard",
    excerpt: "A slow-simmered shank curry, traditionally cooked overnight and eaten for breakfast in old Lahore and Karachi.",
    ingredients: [
      "1.2 kg beef shank with bone marrow",
      "1/2 cup wheat flour, roasted until light brown",
      "1/2 cup cooking oil or ghee",
      "2 onions, sliced and fried golden",
      "3 tbsp ginger-garlic paste",
      "3 tbsp nihari masala (or 1 tsp each: fennel, coriander, cumin, red chilli, garam masala)",
      "1 tsp turmeric powder",
      "Julienned ginger, sliced green chillies, coriander, and lemon wedges to serve",
      "Salt to taste"
    ],
    steps: [
      "Heat oil in a heavy pot, add ginger-garlic paste and cook for 2 minutes, then add all the dry spices and fry briefly.",
      "Add the beef shank and sear on all sides for 8–10 minutes until browned.",
      "Add 2 litres of hot water, bring to a boil, then reduce heat to low, cover, and simmer for 3–4 hours until the meat is fall-apart tender.",
      "Mix the roasted flour with a cup of water into a smooth paste, then stir it into the pot to thicken the gravy. Simmer for another 20 minutes.",
      "Adjust salt and consistency — nihari should be thick enough to coat a spoon.",
      "Serve hot, topped with julienned ginger, green chillies, fried onions, and a squeeze of lemon."
    ],
    tip: "The long simmer is non-negotiable — this is a dish that rewards patience, not high heat."
  },
  {
    slug: "seekh-kebab",
    name: "Seekh Kebab",
    category: "BBQ & Kebab",
    icon: "🍢",
    prepTime: "20 min",
    cookTime: "20 min",
    servings: "4",
    difficulty: "Medium",
    excerpt: "Hand-minced beef or mutton, skewered and grilled over charcoal until charred at the edges.",
    ingredients: [
      "500 g beef or mutton mince, finely ground",
      "1 small onion, grated and squeezed dry",
      "2 tbsp ginger-garlic paste",
      "2 green chillies, finely chopped",
      "1 tsp roasted cumin powder",
      "1 tsp red chilli powder",
      "1/2 tsp garam masala",
      "2 tbsp gram flour (besan), roasted",
      "2 tbsp fresh coriander, finely chopped",
      "1 egg (optional, helps binding)",
      "Salt to taste"
    ],
    steps: [
      "Combine the mince with all ingredients except the skewers, kneading well for 5 minutes until the mixture is smooth and slightly sticky.",
      "Cover and rest in the fridge for at least 30 minutes — this firms up the mixture and makes it easier to shape.",
      "Wet your hands, take a portion of mince, and mould it firmly onto a flat metal skewer into a long sausage shape.",
      "Grill over hot charcoal (or under a broiler), turning every 2–3 minutes, until charred outside and cooked through — about 12–15 minutes total.",
      "Slide off the skewer and serve hot with naan, sliced onions, and mint chutney."
    ],
    tip: "If the mixture won't hold its shape on the skewer, it needs more resting time or a bit more roasted besan to bind it."
  },
  {
    slug: "chapli-kebab",
    name: "Chapli Kebab",
    category: "BBQ & Kebab",
    icon: "🍢",
    prepTime: "20 min",
    cookTime: "20 min",
    servings: "4",
    difficulty: "Medium",
    excerpt: "The flat, crisp-edged Peshawari kebab, loaded with tomato, coriander seed, and pomegranate tang.",
    ingredients: [
      "500 g beef mince",
      "1 large tomato, finely diced (seeds removed)",
      "1 medium onion, finely chopped",
      "2 tbsp coriander seeds, coarsely crushed",
      "1 tbsp cumin seeds, coarsely crushed",
      "2 tbsp dried pomegranate seeds (anardana), crushed",
      "2 green chillies, finely chopped",
      "2 tbsp ginger-garlic paste",
      "3 tbsp cornflour or gram flour",
      "1 egg",
      "1 tsp red chilli powder",
      "Cooking oil, for shallow frying",
      "Salt to taste"
    ],
    steps: [
      "Mix the mince with all ingredients except the oil, combining gently so the tomato and onion don't turn watery.",
      "Rest the mixture in the fridge for 20 minutes to firm up.",
      "Shape into flat, wide patties about 1 cm thick — chapli kebabs are traditionally broader and flatter than seekh kebabs.",
      "Heat a generous layer of oil in a flat pan and shallow-fry the patties for 4–5 minutes per side until deeply browned and cooked through.",
      "Drain briefly on paper towels and serve hot with naan and raw onion rings."
    ],
    tip: "Keep the patties slightly thinner at the edges than the centre — it gives that signature crisp, lacy border."
  },
  {
    slug: "chicken-tikka",
    name: "Chicken Tikka",
    category: "BBQ & Kebab",
    icon: "🍢",
    prepTime: "15 min + 2 hr marinate",
    cookTime: "20 min",
    servings: "4",
    difficulty: "Easy",
    excerpt: "Yogurt-marinated chicken, grilled until smoky — a barbecue-night staple.",
    ingredients: [
      "800 g bone-in chicken pieces (leg and thigh work best)",
      "1 cup plain yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tbsp red chilli powder",
      "1 tsp turmeric powder",
      "1 tbsp roasted cumin powder",
      "1 tsp garam masala",
      "2 tbsp lemon juice",
      "2 tbsp cooking oil",
      "A few drops of orange or red food colour (optional, for the classic tandoori look)",
      "Salt to taste"
    ],
    steps: [
      "Make deep slits in the chicken pieces so the marinade penetrates well.",
      "Mix all the marinade ingredients into a smooth paste and rub thoroughly over the chicken, working it into the slits.",
      "Cover and marinate in the fridge for at least 2 hours, ideally overnight.",
      "Thread onto skewers or arrange on a grill rack, then cook over charcoal or under a hot broiler, turning every 5 minutes, for 20–25 minutes until charred and cooked through.",
      "Rest for 5 minutes, then serve with mint chutney, sliced onions, and lemon wedges."
    ],
    tip: "A brief final blast over direct flame after the chicken is cooked through gives you the char without drying out the meat."
  },
  {
    slug: "haleem",
    name: "Haleem",
    category: "Curry",
    icon: "🍛",
    prepTime: "20 min + overnight soak",
    cookTime: "2.5 hr",
    servings: "8",
    difficulty: "Hard",
    excerpt: "A slow-cooked porridge of wheat, lentils, and shredded meat, pounded down until silky.",
    ingredients: [
      "500 g beef or chicken, bone-in",
      "1 cup broken wheat (daliya)",
      "1/2 cup mixed lentils (chana daal, masoor daal, moong daal), soaked overnight",
      "1/4 cup rice, soaked",
      "2 onions, sliced and fried golden",
      "3 tbsp ginger-garlic paste",
      "1 tbsp red chilli powder",
      "1 tsp turmeric powder",
      "1 tbsp haleem masala or garam masala",
      "1/2 cup ghee",
      "Julienned ginger, chopped coriander, mint, fried onions, green chillies, and lemon to garnish",
      "Salt to taste"
    ],
    steps: [
      "Boil the meat with ginger-garlic paste, turmeric, red chilli powder, and salt in 2 litres of water until fully tender, then shred the meat and reserve the stock.",
      "Separately boil the soaked wheat, lentils, and rice together until completely soft and starting to break down — about 45 minutes.",
      "Blend or mash the wheat-lentil mixture into a coarse, thick paste, adding reserved stock as needed.",
      "Combine the shredded meat, the wheat-lentil paste, and the remaining stock in one large pot. Simmer on low heat for 45 minutes to an hour, stirring often so it doesn't stick.",
      "Beat the haleem vigorously with a wooden spoon (or hand blender) until smooth and porridge-like.",
      "Finish with a tarka of hot ghee poured over the top, then garnish generously with ginger, coriander, mint, fried onions, and a squeeze of lemon."
    ],
    tip: "Stir haleem often while it simmers — it catches and scorches at the bottom far more easily than a regular curry."
  },
  {
    slug: "aloo-keema",
    name: "Aloo Keema",
    category: "Main Course",
    icon: "🍲",
    prepTime: "10 min",
    cookTime: "30 min",
    servings: "4",
    difficulty: "Easy",
    excerpt: "Everyday minced meat and potato curry — the dish most desi households can make with their eyes closed.",
    ingredients: [
      "500 g beef or mutton mince",
      "2 medium potatoes, peeled and cubed",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "1 tsp red chilli powder",
      "1/2 tsp turmeric powder",
      "1 tsp coriander powder",
      "1/2 tsp garam masala",
      "1/3 cup cooking oil",
      "Fresh coriander, chopped",
      "Salt to taste"
    ],
    steps: [
      "Heat oil and fry the onion until golden brown.",
      "Add ginger-garlic paste and cook for a minute, then add the mince, breaking it up well, and cook until it changes colour.",
      "Add tomatoes and all the dry spices, cover, and cook on medium heat for 10 minutes until the tomatoes soften into a gravy.",
      "Add the potatoes and a cup of water, cover, and simmer for 15 minutes until the potatoes are tender and the oil separates.",
      "Garnish with coriander and serve with chapati or plain rice."
    ],
    tip: "Cut the potatoes into slightly smaller cubes than usual — they cook faster and take on more of the keema's flavour."
  },
  {
    slug: "palak-gosht",
    name: "Palak Gosht",
    category: "Curry",
    icon: "🍛",
    prepTime: "15 min",
    cookTime: "50 min",
    servings: "5",
    difficulty: "Medium",
    excerpt: "Mutton simmered down into a deep green spinach gravy — comfort food for a cold evening.",
    ingredients: [
      "600 g mutton, bone-in",
      "500 g spinach, roughly chopped",
      "2 onions, sliced",
      "2 tomatoes, chopped",
      "3 tbsp ginger-garlic paste",
      "2 green chillies",
      "1 tsp red chilli powder",
      "1/2 tsp turmeric powder",
      "1 tsp coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    steps: [
      "Blanch the spinach in boiling water for 2 minutes, then blend into a coarse purée.",
      "Heat oil and fry the onions until golden, then add ginger-garlic paste and cook for 2 minutes.",
      "Add the mutton and sear for 5–6 minutes, then add tomatoes and all dry spices, cooking until the tomatoes break down.",
      "Add 1.5 cups of water, cover, and simmer on low heat for 35–40 minutes until the mutton is tender.",
      "Stir in the spinach purée and green chillies, then simmer uncovered for 10 more minutes until the oil rises to the surface.",
      "Serve hot with naan or boiled rice."
    ],
    tip: "Blanching the spinach first keeps its colour bright green instead of turning a dull olive when it cooks down."
  },
  {
    slug: "chana-chaat",
    name: "Chana Chaat",
    category: "Snacks",
    icon: "🥟",
    prepTime: "15 min",
    cookTime: "5 min",
    servings: "4",
    difficulty: "Easy",
    excerpt: "A tangy, spiced chickpea salad — the go-to street snack for a Ramzan iftar table.",
    ingredients: [
      "2 cups boiled chickpeas (chana)",
      "1 boiled potato, diced",
      "1 small onion, finely chopped",
      "1 tomato, finely chopped",
      "1 green chilli, finely chopped",
      "2 tbsp tamarind chutney",
      "2 tbsp mint-coriander chutney",
      "1 tsp chaat masala",
      "1/2 tsp roasted cumin powder",
      "Juice of 1 lemon",
      "Sev (crispy gram flour noodles), for topping",
      "Fresh coriander, chopped",
      "Salt to taste"
    ],
    steps: [
      "In a large bowl, combine the boiled chickpeas, potato, onion, tomato, and green chilli.",
      "Add tamarind chutney, mint-coriander chutney, chaat masala, roasted cumin, salt, and lemon juice.",
      "Toss everything together gently until well coated.",
      "Transfer to a serving dish, top with sev and fresh coriander, and serve immediately so the sev stays crisp."
    ],
    tip: "Add the sev only right before serving — left to sit, it goes soggy fast."
  },
  {
    slug: "samosa",
    name: "Samosa",
    category: "Snacks",
    icon: "🥟",
    prepTime: "40 min",
    cookTime: "25 min",
    servings: "12 pieces",
    difficulty: "Medium",
    excerpt: "Crisp, golden pastry folded around a spiced potato and pea filling — a teatime essential.",
    ingredients: [
      "12 samosa pastry sheets (store-bought or homemade)",
      "3 medium potatoes, boiled and mashed coarsely",
      "1/2 cup green peas, boiled",
      "1 tsp cumin seeds",
      "1 tsp coriander seeds, crushed",
      "1 tsp red chilli powder",
      "1/2 tsp garam masala",
      "1 tsp dried mango powder (amchoor) or lemon juice",
      "1 green chilli, finely chopped",
      "2 tbsp cooking oil, plus more for frying",
      "Fresh coriander, chopped",
      "1 tbsp flour mixed with water, for sealing",
      "Salt to taste"
    ],
    steps: [
      "Heat 2 tbsp oil, add cumin and coriander seeds, and let them sizzle for 30 seconds.",
      "Add mashed potatoes, peas, green chilli, and all the dry spices. Mix well and cook for 3–4 minutes, then stir in fresh coriander and let the filling cool completely.",
      "Fold each pastry sheet into a cone, seal the side seam with the flour paste, and fill with 2 tablespoons of the potato mixture.",
      "Seal the top edge firmly with more flour paste, pressing out any air pockets.",
      "Heat oil in a deep pan to medium-low heat and fry the samosas in batches for 10–12 minutes, turning occasionally, until golden and crisp.",
      "Drain on paper towels and serve hot with tamarind or mint chutney."
    ],
    tip: "Fry on medium-low, not high heat — samosas need time for the inside to warm through without the outside burning first."
  },
  {
    slug: "gol-gappay",
    name: "Gol Gappay (Pani Puri)",
    category: "Snacks",
    icon: "🥟",
    prepTime: "30 min",
    cookTime: "10 min",
    servings: "4",
    difficulty: "Medium",
    excerpt: "Crisp hollow shells, filled and dunked in spiced tamarind water — best eaten standing up, fast.",
    ingredients: [
      "20 ready-made gol gappay shells (puri)",
      "1 cup boiled chickpeas, lightly mashed",
      "1 boiled potato, diced small",
      "2 tbsp tamarind pulp",
      "1 tsp roasted cumin powder",
      "1 tsp chaat masala",
      "1/2 tsp black salt",
      "1/2 tsp red chilli powder",
      "1 tbsp mint leaves, blended with a little water",
      "3 cups cold water",
      "Salt to taste"
    ],
    steps: [
      "Mix the tamarind pulp, mint water, roasted cumin, chaat masala, black salt, red chilli powder, and salt into the cold water. Taste and adjust — the pani should be tangy, spiced, and a little sour.",
      "Combine the mashed chickpeas and diced potato in a separate bowl as the filling.",
      "Tap a small hole in the top of each gol gappa shell with your thumb, being careful not to crack it.",
      "Fill each shell with a spoonful of the chickpea-potato mixture, then dunk into the spiced water just before eating.",
      "Serve immediately — gol gappay are meant to be eaten the moment they're filled."
    ],
    tip: "Chill the pani for at least an hour before serving — cold pani is non-negotiable for this one."
  },
  {
    slug: "beef-pulao",
    name: "Beef Pulao",
    category: "Rice & Biryani",
    icon: "🍚",
    prepTime: "15 min",
    cookTime: "1 hr",
    servings: "6",
    difficulty: "Medium",
    excerpt: "Lightly spiced rice cooked in its own meat stock — gentler and simpler than biryani, but just as loved.",
    ingredients: [
      "1 kg beef, bone-in, cut into pieces",
      "600 g basmati rice, soaked 30 min",
      "2 onions, sliced",
      "3 tbsp ginger-garlic paste",
      "Whole spices: 4 cloves, 2 black cardamom, 1 cinnamon stick, 1 tsp cumin seeds, 2 bay leaves",
      "1 tsp whole black peppercorns",
      "1/2 cup cooking oil or ghee",
      "Fried onions and coriander, to garnish",
      "Salt to taste"
    ],
    steps: [
      "Heat oil and fry the onions until golden, then remove half for garnish.",
      "Add ginger-garlic paste and whole spices to the remaining onions and cook for 2 minutes.",
      "Add the beef and sear for 5 minutes, then add 1.5 litres of water and salt. Cover and simmer for 40–45 minutes until the beef is tender.",
      "Strain the stock, measuring out exactly double the volume of rice you're using, and set the beef pieces aside.",
      "Bring the measured stock back to a boil, add the drained rice and the beef, cover tightly, and cook on low heat for 18–20 minutes until the rice is fully cooked and the stock is absorbed.",
      "Let it rest for 10 minutes, then fluff gently and garnish with fried onions and coriander."
    ],
    tip: "Measuring the stock precisely (double the rice by volume) is the difference between fluffy pulao and mushy rice — don't eyeball it."
  },
  {
    slug: "daal-chawal",
    name: "Daal Chawal",
    category: "Main Course",
    icon: "🍲",
    prepTime: "10 min",
    cookTime: "30 min",
    servings: "4",
    difficulty: "Easy",
    excerpt: "Lentils and steamed rice — the quiet, everyday meal that shows up on most desi dinner tables.",
    ingredients: [
      "1 cup mixed daal (chana daal and masoor daal), washed",
      "2 cups basmati rice, washed",
      "1 onion, sliced",
      "2 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "1/2 tsp turmeric powder",
      "1/2 tsp red chilli powder",
      "1 tsp cumin seeds",
      "2 dried red chillies",
      "3 tbsp cooking oil or ghee",
      "Fresh coriander, chopped",
      "Salt to taste"
    ],
    steps: [
      "Boil the daal with turmeric and salt in 3 cups of water until soft, about 20 minutes, then lightly mash.",
      "Separately, boil the rice in salted water until tender, then drain and set aside.",
      "Heat oil in a small pan, add cumin seeds and dried red chillies, and let them sizzle for a few seconds.",
      "Add the sliced onion and fry until golden, then add ginger-garlic paste, tomatoes, and red chilli powder, cooking until the tomatoes soften.",
      "Pour this tarka over the boiled daal and simmer together for 5 minutes.",
      "Garnish the daal with coriander and serve hot alongside the steamed rice."
    ],
    tip: "Save the tarka for the very end — pouring hot, sizzling spiced oil over the daal right before serving is what gives it its aroma."
  },
  {
    slug: "chicken-handi",
    name: "Chicken Handi",
    category: "Curry",
    icon: "🍛",
    prepTime: "10 min",
    cookTime: "35 min",
    servings: "4",
    difficulty: "Easy",
    excerpt: "A creamy, restaurant-style chicken curry finished with cream and crushed fenugreek.",
    ingredients: [
      "1 kg chicken, cut into pieces",
      "1 cup plain yogurt",
      "2 onions, finely chopped",
      "2 tomatoes, puréed",
      "3 tbsp ginger-garlic paste",
      "2 green chillies, slit",
      "1 tsp red chilli powder",
      "1/2 tsp turmeric powder",
      "1 tsp garam masala",
      "1/2 cup fresh cream",
      "1 tsp crushed dried fenugreek leaves (kasuri methi)",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    steps: [
      "Heat oil and fry the onions until golden brown, then blend into a smooth paste with a little water.",
      "Return the onion paste to the pan, add ginger-garlic paste, and cook for 2 minutes.",
      "Add tomato purée and all dry spices, cooking until the oil separates.",
      "Add the chicken and yogurt, stirring well, then cover and simmer on medium-low heat for 20 minutes until the chicken is cooked through.",
      "Stir in the cream, green chillies, and crushed fenugreek leaves, then simmer uncovered for 5 more minutes.",
      "Serve hot with naan or steamed rice."
    ],
    tip: "Whisk the yogurt smooth before adding it to the pan, and keep the heat moderate — it helps prevent the curry from splitting."
  },
  {
    slug: "mutton-karahi",
    name: "Mutton Karahi",
    category: "Curry",
    icon: "🍛",
    prepTime: "10 min",
    cookTime: "1 hr",
    servings: "5",
    difficulty: "Medium",
    excerpt: "The mutton version of the classic karahi — richer, slower, and worth every extra minute.",
    ingredients: [
      "1 kg mutton, bone-in, cut into pieces",
      "5 tomatoes, chopped",
      "1/2 cup yogurt",
      "1/2 cup cooking oil",
      "3 tbsp ginger-garlic paste",
      "4–5 green chillies, slit",
      "1 tsp red chilli flakes",
      "1 tsp crushed black pepper",
      "1 tsp cumin seeds",
      "Julienned ginger and coriander, to garnish",
      "Salt to taste"
    ],
    steps: [
      "Heat oil in a karahi, add the mutton, and sear on high heat for 8–10 minutes until browned on all sides.",
      "Add ginger-garlic paste and cumin seeds, cooking for 2 minutes.",
      "Add tomatoes and salt, cover, and cook on medium heat for 15 minutes until the tomatoes soften.",
      "Add 1 cup of water, cover, and simmer on low heat for 35–40 minutes until the mutton is tender, stirring occasionally.",
      "Stir in the yogurt, green chillies, red chilli flakes, and crushed black pepper, then cook uncovered for 8–10 minutes until the oil rises to the top.",
      "Garnish with julienned ginger and coriander, and serve hot with naan."
    ],
    tip: "Mutton needs patience — resist raising the heat to speed things up, or the meat will turn tough instead of tender."
  },
  {
    slug: "reshmi-kebab",
    name: "Reshmi Kebab",
    category: "BBQ & Kebab",
    icon: "🍢",
    prepTime: "20 min + 1 hr marinate",
    cookTime: "20 min",
    servings: "4",
    difficulty: "Medium",
    excerpt: "\"Silky\" kebab — boneless chicken marinated in cream and mild spice, grilled until tender.",
    ingredients: [
      "600 g boneless chicken, cubed",
      "1/2 cup fresh cream",
      "2 tbsp yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tbsp white pepper powder",
      "1 tsp roasted cumin powder",
      "1/2 tsp cardamom powder",
      "1 tbsp lemon juice",
      "2 tbsp cooking oil",
      "Salt to taste"
    ],
    steps: [
      "Combine the chicken with all the marinade ingredients, mixing well to coat every piece.",
      "Cover and marinate in the fridge for at least 1 hour.",
      "Thread the chicken onto skewers, leaving a little space between pieces so they cook evenly.",
      "Grill over charcoal or under a hot broiler for 15–18 minutes, turning occasionally and basting once with a little oil, until lightly charred and cooked through.",
      "Rest for a few minutes before sliding off the skewer, then serve with mint chutney and lemon wedges."
    ],
    tip: "Reshmi kebab is meant to be pale and tender, not deeply charred — keep the heat moderate rather than searing hard."
  },
  {
    slug: "kheer",
    name: "Kheer",
    category: "Dessert",
    icon: "🍮",
    prepTime: "5 min",
    cookTime: "40 min",
    servings: "6",
    difficulty: "Easy",
    excerpt: "Rice pudding simmered slowly in milk until thick and fragrant with cardamom.",
    ingredients: [
      "1/4 cup rice, washed and soaked 20 min",
      "1.5 litres full-fat milk",
      "1/2 cup sugar (adjust to taste)",
      "4 green cardamom pods, crushed",
      "2 tbsp chopped almonds and pistachios",
      "A few strands of saffron",
      "1 tbsp rose water (optional)"
    ],
    steps: [
      "Bring the milk to a boil in a heavy-bottomed pot, then reduce to a gentle simmer.",
      "Drain the soaked rice and add it to the milk, stirring occasionally to prevent it sticking to the bottom.",
      "Simmer on low heat for 30–35 minutes, stirring every few minutes, until the rice is fully soft and the milk has thickened and reduced by about a third.",
      "Add sugar, crushed cardamom, and saffron, and simmer for another 5 minutes until the sugar dissolves.",
      "Stir in rose water if using, then remove from heat — the kheer will thicken further as it cools.",
      "Garnish with chopped almonds and pistachios and serve warm or chilled."
    ],
    tip: "Kheer thickens a lot as it cools, so take it off the heat while it's still slightly looser than you want the final texture to be."
  },
  {
    slug: "gulab-jamun",
    name: "Gulab Jamun",
    category: "Dessert",
    icon: "🍮",
    prepTime: "20 min",
    cookTime: "20 min",
    servings: "16 pieces",
    difficulty: "Medium",
    excerpt: "Soft, deep-fried milk dumplings soaked in rose-scented sugar syrup.",
    ingredients: [
      "1 cup milk powder",
      "3 tbsp all-purpose flour",
      "1/4 tsp baking soda",
      "2 tbsp ghee, melted",
      "3–4 tbsp milk, as needed",
      "Oil or ghee, for deep frying",
      "For the syrup: 1.5 cups sugar, 1.5 cups water, 4 green cardamom pods, 1 tsp rose water"
    ],
    steps: [
      "Make the syrup first: boil sugar and water together for 8–10 minutes until slightly sticky, then add cardamom and rose water and set aside warm.",
      "Mix milk powder, flour, and baking soda, then rub in the melted ghee until the mixture resembles breadcrumbs.",
      "Add milk a little at a time, kneading gently into a soft, smooth dough — avoid overworking it.",
      "Divide into 16 small portions and roll into smooth, crack-free balls.",
      "Heat oil on medium-low heat and fry the balls in batches, stirring gently and constantly, until evenly deep brown all over — about 8–10 minutes per batch.",
      "Drop the hot fried balls directly into the warm syrup and let them soak for at least 1 hour before serving."
    ],
    tip: "Fry on low-medium heat only — jamuns that brown too fast on the outside stay raw and dense in the centre."
  }
];
